import { ResourceType } from '@prisma/client';

/**
 * Dữ liệu mẫu cho blog kiến thức: mỗi bài viết gắn với một hoặc nhiều task trong roadmap,
 * kèm trang tài liệu nội bộ (Markdown) và link tài nguyên ngoài.
 *
 * Task được tham chiếu qua `timelineTitles` — seeder sẽ map title -> id sau khi seed timeline.
 */

export interface DocSeed {
  title: string;
  summary: string;
  content: string;
  order: number;
}

export interface ResourceSeed {
  title: string;
  url: string;
  type: ResourceType;
  note?: string;
}

export interface PostSeed {
  slug: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  tags: string[];
  coverGradient: string; // dùng làm coverImage dạng CSS gradient token (frontend tự render)
  timelineTitles: string[];
  docs: DocSeed[];
  resources: ResourceSeed[];
  /** Mục tiêu học tập ghi ngược lại vào task đầu tiên trong `timelineTitles` */
  objectives?: string[];
}

// Gom nhiều dòng thành Markdown — tránh phải escape dấu backtick của code block.
const md = (...lines: string[]) => lines.join('\n');

export const BLOG_SEED: PostSeed[] = [
  {
    slug: 'aspnet-core-di-container-va-service-lifetime',
    title: '99 Ngày .NET — Ngày 01: DI container & Service Lifetime',
    summary:
      'Container của ASP.NET Core giữ gì, ba vòng đời Singleton/Scoped/Transient khác nhau ra sao và lỗi captive dependency hay gặp.',
    category: 'Backend',
    tags: ['dotnet', 'aspnet-core', 'di'],
    coverGradient: 'gradient:violet',
    timelineTitles: ['Tháng 2 — ASP.NET Core + EF Core + Ticketing CRUD'],
    objectives: [
      'Giải thích được IoC/DI và vì sao ASP.NET Core dựng sẵn container',
      'Chọn đúng Singleton / Scoped / Transient cho từng loại service',
      'Nhận ra và sửa lỗi captive dependency',
      'Đăng ký service theo interface để test dễ hơn',
    ],
    content: md(
      'Ngày đầu tiên của chuỗi .NET không bắt đầu bằng controller hay EF Core, mà bằng thứ đứng dưới tất cả: **DI container**. Hiểu sai vòng đời service là nguồn gốc của phần lớn bug "chạy máy mình thì được".',
      '',
      '## Dependency Injection là gì?',
      '',
      'Thay vì class tự `new` thứ nó cần, ta **khai báo** thứ nó cần ở constructor rồi để container tự đưa vào. Class chỉ còn phụ thuộc vào abstraction:',
      '',
      '```csharp',
      'public class TicketService',
      '{',
      '    private readonly ITicketRepository _repository;',
      '    private readonly ILogger<TicketService> _logger;',
      '',
      '    // Container nhìn constructor và tự truyền các phụ thuộc vào',
      '    public TicketService(ITicketRepository repository, ILogger<TicketService> logger)',
      '    {',
      '        _repository = repository;',
      '        _logger = logger;',
      '    }',
      '}',
      '```',
      '',
      'Lợi ích thực tế: đổi implementation không phải sửa class dùng nó, và khi viết unit test chỉ cần truyền một fake repository vào constructor.',
      '',
      '## Container — nơi khai báo "cái gì đổi thành cái gì"',
      '',
      'Trong `Program.cs`, mọi thứ được đăng ký vào `IServiceCollection` trước khi app build:',
      '',
      '```csharp',
      'var builder = WebApplication.CreateBuilder(args);',
      '',
      'builder.Services.AddScoped<ITicketRepository, TicketRepository>();',
      'builder.Services.AddScoped<TicketService>();',
      'builder.Services.AddSingleton<IClock, SystemClock>();',
      'builder.Services.AddTransient<IEmailSender, SmtpEmailSender>();',
      '',
      'var app = builder.Build();',
      '```',
      '',
      'Sau `builder.Build()`, container đã "đóng băng": muốn thêm service thì phải đăng ký trước đó.',
      '',
      '## Ba vòng đời — chọn sai là hỏng',
      '',
      '| Vòng đời | Tạo mới khi nào | Dùng cho |',
      '| --- | --- | --- |',
      '| `Singleton` | Một lần cho cả app | Cache, config đã đọc, clock, HTTP client factory |',
      '| `Scoped` | Một lần mỗi HTTP request | `DbContext`, repository, service nghiệp vụ |',
      '| `Transient` | Mỗi lần được inject | Service nhẹ, không giữ state |',
      '',
      'Quy tắc dễ nhớ: **cái gì gắn với một request thì Scoped**. `DbContext` là ví dụ kinh điển — nó theo dõi entity trong một unit of work, dùng chung giữa các request là sai.',
      '',
      '## Captive dependency — cái bẫy hay gặp nhất',
      '',
      'Một `Singleton` inject vào một `Scoped` thì service Scoped đó bị "giam" lại: nó được tạo một lần rồi sống mãi theo Singleton.',
      '',
      '```csharp',
      '// SAI: CacheWarmer là Singleton nhưng giữ DbContext (Scoped) suốt vòng đời app',
      'public class CacheWarmer',
      '{',
      '    private readonly AppDbContext _db; // bị giam',
      '    public CacheWarmer(AppDbContext db) => _db = db;',
      '}',
      '',
      '// ĐÚNG: xin scope mới mỗi lần cần dùng',
      'public class CacheWarmer',
      '{',
      '    private readonly IServiceScopeFactory _scopeFactory;',
      '    public CacheWarmer(IServiceScopeFactory scopeFactory) => _scopeFactory = scopeFactory;',
      '',
      '    public async Task WarmAsync()',
      '    {',
      '        using var scope = _scopeFactory.CreateScope();',
      '        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();',
      '        // ... dùng db trong phạm vi scope này',
      '    }',
      '}',
      '```',
      '',
      '> Bật `ValidateScopes` ở môi trường Development (mặc định đã bật) để container ném lỗi ngay khi phát hiện captive dependency, thay vì để bug âm ỉ.',
      '',
      '## Bài tập nhỏ',
      '',
      '1. Đăng ký `ITicketRepository` theo cả ba vòng đời rồi log `GetHashCode()` của instance ở hai request khác nhau — quan sát khác biệt.',
      '2. Cố tình inject `AppDbContext` vào một `Singleton` và đọc thông báo lỗi container ném ra.',
      '3. Viết một `IClock` giả cho unit test, thay `SystemClock` bằng nó và kiểm tra logic hết hạn SLA.',
      '4. Trong dự án Ticketing, liệt kê mọi service đang đăng ký và giải thích tại sao chọn vòng đời đó.',
      '',
      '## Kết luận',
      '',
      'DI container không phải phép màu — nó chỉ là một cuốn sổ ánh xạ *interface → implementation* kèm quy tắc vòng đời. Nắm ba vòng đời và bẫy captive dependency là đủ để đi tiếp sang **Ngày 02: Middleware pipeline & ProblemDetails**.',
    ),
    docs: [
      {
        title: 'Cheatsheet: chọn vòng đời service trong ASP.NET Core',
        summary: 'Bảng tra nhanh Singleton / Scoped / Transient kèm ví dụ và các lỗi thường gặp.',
        order: 0,
        content: md(
          '## Bảng tra nhanh',
          '',
          '| Service | Vòng đời | Lý do |',
          '| --- | --- | --- |',
          '| `AppDbContext` | Scoped | Theo dõi entity trong một unit of work |',
          '| Repository | Scoped | Đi kèm `DbContext` |',
          '| Handler nghiệp vụ (MediatR) | Scoped | Chạy trong phạm vi một request |',
          '| `IMemoryCache` | Singleton | Chia sẻ dữ liệu toàn app |',
          '| `IOptions<T>` | Singleton | Config đọc một lần |',
          '| `IEmailSender` | Transient | Nhẹ, không giữ state |',
          '',
          '## Checklist khi thêm service mới',
          '',
          '- [ ] Service có giữ state không? Có → cân nhắc Scoped/Singleton, không → Transient.',
          '- [ ] State đó có gắn với một request không? Có → Scoped.',
          '- [ ] Service này có inject thứ gì vòng đời ngắn hơn nó không? Có → sửa lại (captive dependency).',
          '- [ ] Có cần mock trong test không? Có → đăng ký qua interface.',
          '',
          '## Ba lỗi hay gặp',
          '',
          '```csharp',
          '// 1. Đăng ký implementation thay vì interface -> không mock được',
          'builder.Services.AddScoped<TicketRepository>();          // khó test',
          'builder.Services.AddScoped<ITicketRepository, TicketRepository>(); // nên dùng',
          '',
          '// 2. Resolve thủ công từ ServiceProvider ở khắp nơi (service locator anti-pattern)',
          'var repo = provider.GetRequiredService<ITicketRepository>(); // chỉ dùng ở composition root',
          '',
          '// 3. Quên Dispose khi tự tạo scope',
          'using var scope = scopeFactory.CreateScope(); // nhớ using',
          '```',
        ),
      },
      {
        title: 'Sổ tay: thứ tự đăng ký service cho dự án Ticketing',
        summary: 'Bố cục Program.cs gọn gàng bằng extension method theo từng nhóm.',
        order: 1,
        content: md(
          '## Vấn đề',
          '',
          '`Program.cs` phình to rất nhanh khi mỗi feature lại thêm vài dòng `AddScoped`.',
          '',
          '## Cách chia',
          '',
          '```csharp',
          '// Infrastructure/DependencyInjection.cs',
          'public static class InfrastructureRegistration',
          '{',
          '    public static IServiceCollection AddInfrastructure(',
          '        this IServiceCollection services, IConfiguration config)',
          '    {',
          '        services.AddDbContext<AppDbContext>(o =>',
          '            o.UseSqlServer(config.GetConnectionString("Default")));',
          '        services.AddScoped<ITicketRepository, TicketRepository>();',
          '        return services;',
          '    }',
          '}',
          '```',
          '',
          '```csharp',
          '// Program.cs sau khi gom nhóm',
          'builder.Services',
          '    .AddApplication()      // MediatR, FluentValidation, mapping',
          '    .AddInfrastructure(builder.Configuration) // DbContext, repository, cache',
          '    .AddWebApi();          // controller, swagger, auth, CORS',
          '```',
          '',
          '## Nguyên tắc',
          '',
          '- Mỗi layer tự chịu trách nhiệm đăng ký service của mình.',
          '- `Program.cs` chỉ còn là mục lục — đọc là biết app gồm những gì.',
          '- Không để layer trong (Application) biết về layer ngoài (Infrastructure).',
        ),
      },
    ],
    resources: [
      {
        title: 'Dependency injection in ASP.NET Core — Microsoft Learn',
        url: 'https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection',
        type: ResourceType.Docs,
        note: 'Đọc kỹ mục Service lifetimes và Scope validation.',
      },
      {
        title: 'Dependency injection guidelines',
        url: 'https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines',
        type: ResourceType.Docs,
        note: 'Danh sách anti-pattern nên tránh, đọc trước khi review code.',
      },
    ],
  },

  {
    slug: 'sliding-window-tu-a-den-z',
    title: 'NeetCode Pattern — Sliding Window từ A đến Z',
    summary:
      'Nhận diện bài Sliding Window trong 10 giây, hai biến thể cửa sổ cố định và cửa sổ co giãn, kèm template code dùng lại được.',
    category: 'Thuật toán',
    tags: ['neetcode', 'sliding-window', 'two-pointers'],
    coverGradient: 'gradient:teal',
    timelineTitles: ['NeetCode Phase 1 — Nền tảng', '90 ngày đầu — Tuần 4: CQRS create ticket'],
    objectives: [
      'Nhận ra bài toán thuộc dạng Sliding Window qua đề bài',
      'Viết được template cửa sổ cố định và cửa sổ co giãn',
      'Phân tích được vì sao độ phức tạp là O(n) chứ không phải O(n²)',
    ],
    content: md(
      'Sliding Window là pattern trả về nhiều điểm nhất trên mỗi giờ ôn: nắm một template là giải được cả chục bài Medium.',
      '',
      '## Khi nào là Sliding Window?',
      '',
      'Đề bài gần như luôn có ba yếu tố:',
      '',
      '1. Dữ liệu là **mảng hoặc chuỗi liên tục** (subarray, substring — không phải subsequence).',
      '2. Hỏi về **tối ưu hoặc đếm**: dài nhất, ngắn nhất, tổng lớn nhất, bao nhiêu đoạn thoả điều kiện.',
      '3. Có một **điều kiện kiểm tra được tăng dần**: tổng, số ký tự khác nhau, số lần xuất hiện.',
      '',
      '> Nếu đề nói "subsequence" (không liên tục) thì đây **không** phải Sliding Window — nhiều khả năng là DP.',
      '',
      '## Biến thể 1 — cửa sổ cố định',
      '',
      'Kích thước `k` cho trước, chỉ cần trượt và cập nhật tổng:',
      '',
      '```python',
      'def max_sum_k(nums, k):',
      '    window = sum(nums[:k])',
      '    best = window',
      '    for right in range(k, len(nums)):',
      '        window += nums[right] - nums[right - k]  # thêm phải, bớt trái',
      '        best = max(best, window)',
      '    return best',
      '```',
      '',
      'Mỗi phần tử vào cửa sổ đúng một lần và ra đúng một lần → **O(n)**.',
      '',
      '## Biến thể 2 — cửa sổ co giãn (hay gặp hơn)',
      '',
      'Cửa sổ nở về bên phải, co lại từ bên trái khi vi phạm điều kiện:',
      '',
      '```python',
      'def longest_unique(s: str) -> int:',
      '    seen = {}          # ký tự -> vị trí cuối cùng',
      '    left = 0',
      '    best = 0',
      '',
      '    for right, ch in enumerate(s):',
      '        if ch in seen and seen[ch] >= left:',
      '            left = seen[ch] + 1      # co cửa sổ, bỏ qua bản trùng',
      '        seen[ch] = right',
      '        best = max(best, right - left + 1)',
      '',
      '    return best',
      '```',
      '',
      'Bản C# tương ứng, dùng khi luyện chung với dự án .NET:',
      '',
      '```csharp',
      'public int LongestUnique(string s)',
      '{',
      '    var seen = new Dictionary<char, int>();',
      '    int left = 0, best = 0;',
      '',
      '    for (int right = 0; right < s.Length; right++)',
      '    {',
      '        if (seen.TryGetValue(s[right], out int last) && last >= left)',
      '            left = last + 1;',
      '',
      '        seen[s[right]] = right;',
      '        best = Math.Max(best, right - left + 1);',
      '    }',
      '',
      '    return best;',
      '}',
      '```',
      '',
      '## Template chung',
      '',
      '```text',
      'left = 0',
      'for right in range(n):',
      '    thêm phần tử right vào cửa sổ',
      '    while cửa sổ vi phạm điều kiện:',
      '        bỏ phần tử left ra khỏi cửa sổ',
      '        left += 1',
      '    cập nhật đáp án bằng cửa sổ hiện tại',
      '```',
      '',
      'Chỉ có hai chỗ cần suy nghĩ cho mỗi bài: **"vi phạm" nghĩa là gì** và **cập nhật đáp án ở đâu** (trong hay ngoài vòng while).',
      '',
      '## Lộ trình bài tập',
      '',
      '| Bài | Mức | Biến thể |',
      '| --- | --- | --- |',
      '| Best Time to Buy and Sell Stock | Easy | Cửa sổ co giãn tối giản |',
      '| Longest Substring Without Repeating Characters | Medium | Co giãn + hash map |',
      '| Longest Repeating Character Replacement | Medium | Co giãn + đếm tần suất |',
      '| Permutation in String | Medium | Cửa sổ cố định + so khớp tần suất |',
      '| Minimum Window Substring | Hard | Co giãn + bộ đếm thiếu/đủ |',
      '',
      '## Kết luận',
      '',
      'Làm đủ 5 bài trên trong một tuần, viết lại template vào sổ pattern bằng lời của mình. Bài kế tiếp trong chuỗi: **Two Pointers — khi nào chạy ngược chiều, khi nào cùng chiều**.',
    ),
    docs: [
      {
        title: 'Template code Sliding Window (Python + C#)',
        summary: 'Hai template dán vào là chạy, kèm chỗ cần sửa cho từng bài.',
        order: 0,
        content: md(
          '## Cửa sổ co giãn — Python',
          '',
          '```python',
          'from collections import Counter',
          '',
          'def solve(s: str, limit: int) -> int:',
          '    count = Counter()',
          '    left = 0',
          '    best = 0',
          '',
          '    for right, ch in enumerate(s):',
          '        count[ch] += 1',
          '',
          '        while len(count) > limit:        # <-- sửa điều kiện theo đề',
          '            count[s[left]] -= 1',
          '            if count[s[left]] == 0:',
          '                del count[s[left]]',
          '            left += 1',
          '',
          '        best = max(best, right - left + 1)',
          '',
          '    return best',
          '```',
          '',
          '## Cửa sổ cố định — C#',
          '',
          '```csharp',
          'public int MaxSumOfK(int[] nums, int k)',
          '{',
          '    int window = 0;',
          '    for (int i = 0; i < k; i++) window += nums[i];',
          '',
          '    int best = window;',
          '    for (int right = k; right < nums.Length; right++)',
          '    {',
          '        window += nums[right] - nums[right - k];',
          '        best = Math.Max(best, window);',
          '    }',
          '    return best;',
          '}',
          '```',
          '',
          '## Ba câu tự hỏi trước khi code',
          '',
          '1. Cửa sổ của mình đang giữ **cái gì** (tổng, bộ đếm, tập ký tự)?',
          '2. Điều kiện **vi phạm** là gì?',
          '3. Đáp án cập nhật khi cửa sổ **hợp lệ** hay khi vừa **co xong**?',
        ),
      },
      {
        title: 'Sổ lỗi: những chỗ hay sai khi làm Sliding Window',
        summary: 'Danh sách lỗi tự tổng hợp sau mỗi lần làm sai, cập nhật dần.',
        order: 1,
        content: md(
          '## Lỗi 1 — cập nhật đáp án sai chỗ',
          '',
          'Với bài "đoạn dài nhất", đáp án cập nhật **sau** vòng `while` (khi cửa sổ đã hợp lệ).',
          'Với bài "đoạn ngắn nhất", đáp án cập nhật **trong** vòng `while` (ngay trước khi co).',
          '',
          '## Lỗi 2 — quên xoá key khỏi map',
          '',
          '```python',
          'count[s[left]] -= 1',
          "if count[s[left]] == 0:",
          '    del count[s[left]]   # thiếu dòng này thì len(count) sai',
          '```',
          '',
          '## Lỗi 3 — nhầm subsequence với substring',
          '',
          'Đọc kỹ đề: "contiguous" / "substring" mới là Sliding Window.',
          '',
          '## Lỗi 4 — off-by-one khi tính độ dài',
          '',
          'Độ dài cửa sổ luôn là `right - left + 1`, không phải `right - left`.',
        ),
      },
    ],
    resources: [
      {
        title: 'NeetCode — Sliding Window playlist',
        url: 'https://neetcode.io/roadmap',
        type: ResourceType.Course,
        note: 'Xem lời giải sau khi đã tự làm 20 phút.',
      },
      {
        title: 'LeetCode 76 — Minimum Window Substring',
        url: 'https://leetcode.com/problems/minimum-window-substring/',
        type: ResourceType.Article,
        note: 'Bài chốt hạ của pattern này, làm được là nắm chắc.',
      },
    ],
  },

  {
    slug: 'ielts-writing-task-2-khung-bai-4-doan',
    title: 'IELTS Writing Task 2 — khung bài 4 đoạn dùng được cho mọi đề',
    summary:
      'Một khung bài cố định cho Task 2: mở bài 2 câu, hai đoạn thân bài theo công thức PEEL, kết bài 1 câu — kèm ngân hàng cụm từ.',
    category: 'IELTS',
    tags: ['ielts', 'writing', 'task-2'],
    coverGradient: 'gradient:amber',
    timelineTitles: ['IELTS Giai đoạn 2 — Kỹ năng IELTS'],
    objectives: [
      'Viết được mở bài Task 2 trong 3 phút',
      'Triển khai thân bài theo cấu trúc PEEL có ví dụ cụ thể',
      'Tự chấm bài theo 4 tiêu chí band descriptor',
    ],
    content: md(
      'Band 6.5 Writing không đòi hỏi ý tưởng độc đáo — nó đòi hỏi **bài viết đúng cấu trúc, đủ ý, đúng ngữ pháp**. Khung dưới đây dùng lại được cho hầu hết đề Task 2.',
      '',
      '## Phân bổ thời gian 40 phút',
      '',
      '| Giai đoạn | Thời gian | Việc cần làm |',
      '| --- | --- | --- |',
      '| Phân tích đề + lên ý | 5 phút | Gạch chân keyword, chọn 2 ý chính |',
      '| Viết | 30 phút | Bám khung, không dừng lại sửa câu |',
      '| Soát lỗi | 5 phút | Chia thì, số ít/nhiều, mạo từ |',
      '',
      '## Khung 4 đoạn',
      '',
      '```text',
      'Mở bài   (2 câu):  paraphrase đề + nêu quan điểm',
      'Thân 1   (5 câu):  Point - Explain - Example - Link',
      'Thân 2   (5 câu):  Point - Explain - Example - Link',
      'Kết bài  (1 câu):  nhắc lại quan điểm bằng từ khác',
      '```',
      '',
      '## Mở bài — 2 câu là đủ',
      '',
      '> **Câu 1:** paraphrase đề bài (đổi từ vựng, đổi cấu trúc, giữ nguyên nghĩa).',
      '> **Câu 2:** trả lời thẳng câu hỏi — đồng ý, phản đối, hay một phần.',
      '',
      'Ví dụ với đề *"Some people think that governments should invest more in public transport than in roads."*:',
      '',
      '```text',
      'It is sometimes argued that public funding ought to be directed towards',
      'public transport systems rather than road construction.',
      'While improved roads bring short-term relief, I believe investment in',
      'public transport offers greater long-term benefits.',
      '```',
      '',
      '## Thân bài — công thức PEEL',
      '',
      '- **P**oint — câu chủ đề, nêu một ý duy nhất.',
      '- **E**xplain — giải thích cơ chế: *vì sao* điều đó xảy ra.',
      '- **E**xample — ví dụ cụ thể, có số liệu hoặc bối cảnh thật.',
      '- **L**ink — nối lại với câu hỏi của đề.',
      '',
      'Lỗi phổ biến nhất ở band 5.5–6.0 là viết 4 ý mỏng thay vì 2 ý sâu. Giám khảo chấm **độ phát triển ý**, không chấm số lượng ý.',
      '',
      '## Ngân hàng cụm từ theo chức năng',
      '',
      '| Chức năng | Cụm dùng được |',
      '| --- | --- |',
      '| Nêu quan điểm | *I would argue that…*, *In my view…* |',
      '| Giải thích | *This is largely because…*, *As a result…* |',
      '| Ví dụ | *A case in point is…*, *This is illustrated by…* |',
      '| Nhượng bộ | *Admittedly…*, *While it is true that…* |',
      '| Kết luận | *On balance…*, *Taking everything into account…* |',
      '',
      '## Tự chấm sau khi viết',
      '',
      '1. **Task Response** — đã trả lời đủ mọi phần của câu hỏi chưa?',
      '2. **Coherence & Cohesion** — mỗi đoạn có đúng một ý chính chưa?',
      '3. **Lexical Resource** — có lặp từ của đề quá 3 lần không?',
      '4. **Grammatical Range** — có ít nhất 3 câu phức đúng ngữ pháp chưa?',
      '',
      '## Kết luận',
      '',
      'Viết 2 bài mỗi tuần theo đúng khung này, mỗi bài ghi lại 3 lỗi vào error log. Sau 6 tuần bạn sẽ viết mở bài trong 3 phút mà không cần nghĩ.',
    ),
    docs: [
      {
        title: 'Error log mẫu — Writing Task 2',
        summary: 'Bảng ghi lỗi sau mỗi bài viết, phân loại theo 4 tiêu chí chấm.',
        order: 0,
        content: md(
          '## Cách dùng',
          '',
          'Sau mỗi bài viết, ghi tối đa 3 lỗi. Ít mà sửa được còn hơn nhiều mà bỏ qua.',
          '',
          '| Ngày | Đề | Lỗi | Tiêu chí | Sửa thành |',
          '| --- | --- | --- | --- | --- |',
          '| 12/08 | Public transport | Thiếu ví dụ ở thân 2 | Task Response | Thêm ví dụ Singapore ERP |',
          '| 15/08 | Online learning | Lặp "student" 7 lần | Lexical | learners / pupils / undergraduates |',
          '| 19/08 | Working from home | Sai thì ở câu điều kiện | Grammar | *If companies allowed…, employees would…* |',
          '',
          '## Ba nhóm lỗi lặp lại nhiều nhất',
          '',
          '1. Mạo từ `a / an / the` với danh từ chung.',
          '2. Chia số ít/số nhiều sau `the number of` và `a number of`.',
          '3. Dùng `people think` thay vì cấu trúc bị động học thuật `it is widely believed that`.',
        ),
      },
    ],
    resources: [
      {
        title: 'IELTS Writing Task 2 band descriptors (public version)',
        url: 'https://www.ielts.org/-/media/pdfs/writing-band-descriptors-task-2.ashx',
        type: ResourceType.Docs,
        note: 'Đọc mô tả band 6 và band 7 để biết khoảng cách cần lấp.',
      },
      {
        title: 'Cambridge IELTS — sample answers',
        url: 'https://www.cambridgeenglish.org/exams-and-tests/ielts/',
        type: ResourceType.Article,
        note: 'So bài mình với sample band 7 cùng đề.',
      },
    ],
  },
];
